from dotenv import load_dotenv
import os

# TO CONFIGURE, DO NOT EDIT THIS FILE. EDIT .env IN THE PARENT DIRECTORY

load_dotenv()

config_archive = os.getenv("archive", 'False').lower() in ('true', '1', 't')
config_archive_dir = os.getenv('archive_dir', 'var/cache')
config_telegramAllowedUserIDs = os.getenv('config_telegramAllowedUserIDs', '').split()
config_telegramBotToken = os.getenv('telegramBotToken', False)
config_telegramOutgoingToken = os.getenv('telegramOutgoingToken', False)
config_telegramOutgoingWebhook = os.getenv('telegramOutgoingWebhook', False)
config_http_timeout = int(os.getenv('http_timeout', 10))
config_openai_api_key = os.getenv('openai_api_key', False)
config_openai_organization = os.getenv('openai_organization', False)
config_slackOAuthToken = os.getenv('slackOAuthToken', False)
config_slackOutgoingToken = os.getenv('slackOutgoingToken', False)
config_ip = os.getenv('ip', '127.0.0.1')
config_port = int(os.getenv('port', 5000))
debug = os.getenv("debug", 'False').lower() in ('true', '1', 't')

webhooks = {}
if os.getenv('slack_webhook'):
    webhooks['slack'] = os.getenv('slack_webhook')
if os.getenv('discord_webhook'):
    webhooks['discord'] = os.getenv('discord_webhook')
if os.getenv('telegramBotToken'):
    webhooks['telegram'] = 'https://api.telegram.org/bot' + os.getenv('telegramBotToken') + '/'

